AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - vendor/bundle/**/*
    - bin/*
    - Gemfile*
    - node_modules/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/AbcSize:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/FrozenStringLiteralComment:
  Enabled: false
