development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE'] %>
  host: <%= ENV['HOST'] %>
  pool: <%= ENV['POOL'] %>
  username: <%= ENV['NAME'] %>
  password: <%= ENV['PASSWORD'] %>
